pool:
  name: Azure Pipelines

steps:
- script: 'npm install'
  displayName: 'Install Dependencies'

- script: |
   npm run build
  displayName: 'Build the project'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'next13cookbookdrop'
    publishLocation: 'Container'